import { Injectable } from '@angular/core';
import { Property } from '../models/property.model';

@Injectable({ providedIn: 'root' })
export class PropertyService {
  private properties: Property[] = [
    {
      id: 1,
      slug: 'maison-aylmer-gatineau',
      title: 'Maison familiale à Aylmer',
      address: '142 Rue des Érables, Aylmer',
      city: 'Gatineau',
      type: 'Maison',
      status: 'active',
      featured: true,
      isNew: true,
      price: 749000,
      bedrooms: 4,
      bathrooms: 3,
      area: 2400,
      lotSize: 8200,
      yearBuilt: 2018,
      municipalEvaluation: 685000,
      municipalTax: 6120,
      schoolTax: 820,
      description: 'Magnifique maison contemporaine offrant des espaces de vie lumineux et une cuisine haut de gamme avec îlot central. Grandes fenêtres, planchers de bois franc et finitions de qualité supérieure. Cour privée aménagée avec terrasse, idéale pour recevoir.',
      features: ['Planchers de bois franc', 'Cuisine avec îlot', 'Garage double', 'Terrasse privée', 'Sous-sol aménagé', 'Système de climatisation central'],
      photos: [
        { url: '/listing/modern_interior.png', alt: 'Cuisine moderne avec îlot central', description: 'Bright cream kitchen with large island, pale cabinetry, pendant lights' },
        { url: '/listing/bedroom.png', alt: 'Chambre principale', description: 'Minimal cream bedroom, layered beige bedding, tall window' },
        { url: '/listing/bathroom.png', alt: 'Salle de bain', description: 'Bright spa-like bathroom, stone surfaces, large windows' },
        { url: '/listing/sofa_interior.png', alt: 'Salon lumineux', description: 'Cozy living room with fireplace and warm wood tones' },
        { url: '/listing/table_dining.png', alt: 'Salle à manger', description: 'Elegant dining area with warm wood tones' },
      ]
    },
    {
      id: 2,
      slug: 'condo-gatineau-centre',
      title: 'Condo moderne au centre-ville',
      address: '580 Boul. Gréber, Apt 12',
      city: 'Gatineau',
      type: 'Condo',
      status: 'active',
      featured: true,
      isNew: false,
      price: 398000,
      bedrooms: 2,
      bathrooms: 2,
      area: 1100,
      yearBuilt: 2020,
      municipalEvaluation: 365000,
      municipalTax: 3250,
      schoolTax: 440,
      description: 'Condo haut de gamme avec vue panoramique, finitions premium et terrasse privée. Stationnement intérieur inclus. Accès direct au corridor de transport actif.',
      features: ['Vue panoramique', 'Terrasse privée', 'Stationnement intérieur', 'Concierge', 'Gym sur place', 'Quartz et acier inoxydable'],
      photos: [
        { url: '/listing/condo_luxurious.png', alt: 'Salon avec vue panoramique', description: 'Modern condo living room with floor-to-ceiling windows, city view' },
        { url: '/listing/modern_interior.png', alt: 'Cuisine contemporaine', description: 'Sleek kitchen with quartz countertops and stainless appliances' },
        { url: '/listing/bathroom.png', alt: 'Salle de bain luxueuse', description: 'Bright spa-like bathroom, stone surfaces, large windows' },
        { url: '/listing/sofa_interior.png', alt: 'Espace détente', description: 'Cozy lounge area with designer furniture' },
        { url: '/sold/front.png', alt: 'Façade de l\'immeuble', description: 'Contemporary building exterior with modern facade' },
      ]
    },
    {
      id: 3,
      slug: 'maison-hull-gatineau',
      title: 'Cottage rénové à Hull',
      address: '38 Rue Taché, Hull',
      city: 'Gatineau',
      type: 'Maison',
      status: 'active',
      featured: false,
      isNew: false,
      price: 529000,
      bedrooms: 3,
      bathrooms: 2,
      area: 1850,
      lotSize: 5400,
      yearBuilt: 1995,
      municipalEvaluation: 495000,
      municipalTax: 4420,
      schoolTax: 595,
      description: 'Charmant cottage entièrement rénové à deux pas du parc Brébeuf. Rénovations complètes en 2022 incluant cuisine, salles de bain et toiture. Cour intime avec pergola.',
      features: ['Rénové en 2022', 'Cuisine rénovée', 'Pergola', 'À deux pas du parc', 'Fenêtres PVC', 'Rangement abondant'],
      photos: [
        { url: '/listing/sofa_interior.png', alt: 'Salon cosy', description: 'Cozy living room with fireplace and warm wood tones' },
        { url: '/listing/table_dining.png', alt: 'Salle à manger', description: 'Elegant dining area with warm wood tones' },
        { url: '/listing/modern_interior.png', alt: 'Cuisine rénovée', description: 'Bright cream kitchen with large island, pale cabinetry, pendant lights' },
        { url: '/listing/bedroom.png', alt: 'Chambre principale', description: 'Minimal cream bedroom, layered beige bedding, tall window' },
        { url: '/listing/bathroom.png', alt: 'Salle de bain rénovée', description: 'Bright spa-like bathroom, stone surfaces, large windows' },
      ]
    },
    {
      id: 4,
      slug: 'jumele-gatineau-ouest',
      title: 'Jumelé spacieux à Gatineau-Ouest',
      address: '910 Rue Maloney Est',
      city: 'Gatineau',
      type: 'Jumelé',
      status: 'active',
      featured: false,
      isNew: true,
      price: 449000,
      bedrooms: 3,
      bathrooms: 2,
      area: 1680,
      lotSize: 4200,
      yearBuilt: 2015,
      municipalEvaluation: 415000,
      municipalTax: 3710,
      schoolTax: 500,
      description: 'Semi-détaché bien entretenu dans un quartier familial tranquille. Double garage, sous-sol partiellement aménagé et cour clôturée. Proche des écoles et des transports.',
      features: ['Garage double', 'Sous-sol aménagé', 'Cour clôturée', 'Proche des écoles', 'Thermopompe', 'Entrée en béton'],
      photos: [
        { url: '/listing/table_dining.png', alt: 'Salle à manger ouverte', description: 'Contemporary kitchen with breakfast bar' },
        { url: '/listing/modern_interior.png', alt: 'Salon', description: 'Bright open-concept living room with neutral palette' },
        { url: '/listing/sofa_interior.png', alt: 'Espace salon', description: 'Cozy living room with warm wood tones' },
        { url: '/listing/bedroom.png', alt: 'Chambre', description: 'Minimal cream bedroom, layered beige bedding, tall window' },
        { url: '/sold/front.png', alt: 'Extérieur', description: 'Well-maintained semi-detached exterior view' },
      ]
    },
    {
      id: 5,
      slug: 'maison-de-luxe-chelsea',
      title: 'Propriété de luxe à Chelsea',
      address: '21 Ch. du Lac Meech',
      city: 'Chelsea',
      type: 'Maison',
      status: 'active',
      featured: true,
      isNew: false,
      price: 1395000,
      bedrooms: 5,
      bathrooms: 4,
      area: 4200,
      lotSize: 24000,
      yearBuilt: 2016,
      municipalEvaluation: 1250000,
      municipalTax: 11200,
      schoolTax: 1500,
      description: 'Résidence d\'exception au cœur du parc de la Gatineau, à quelques pas du lac Meech. Architecture contemporaine, matériaux nobles et vues sur la forêt. Piscine intérieure et spa privé.',
      features: ['Vue sur forêt', 'Piscine intérieure', 'Spa privé', 'Cave à vin', 'Domotique', 'Garage triple'],
      photos: [
        { url: '/listing/bedroom.png', alt: 'Suite principale', description: 'Master suite with walk-in closet and ensuite spa bathroom' },
        { url: '/listing/bathroom.png', alt: 'Salle de bain spa', description: 'Spa-like bathroom with premium stone finishes' },
        { url: '/listing/condo_luxurious.png', alt: 'Grande salle ouverte', description: 'Grand open living space with cathedral ceiling' },
        { url: '/listing/modern_interior.png', alt: 'Cuisine gastronomique', description: 'Gourmet kitchen with premium finishes and large island' },
        { url: '/listing/sofa_interior.png', alt: 'Salon de détente', description: 'Elegant lounge area overlooking the forest' },
      ]
    },
    {
      id: 6,
      slug: 'condo-ottawa-gatineau',
      title: 'Condo neuf près d\'Ottawa',
      address: '1200 Boul. Alexandre-Taché, Apt 8',
      city: 'Gatineau',
      type: 'Condo',
      status: 'active',
      featured: false,
      isNew: true,
      price: 319000,
      bedrooms: 1,
      bathrooms: 1,
      area: 750,
      yearBuilt: 2023,
      municipalEvaluation: 295000,
      municipalTax: 2640,
      schoolTax: 355,
      description: 'Condo neuf livraison immédiate. Finitions modernes, balcon est et vue dégagée. À moins de 5 minutes du pont Alexandra. Stationnement intérieur chauffé inclus.',
      features: ['Neuf 2023', 'Balcon est', 'Stationnement chauffé', 'Proche pont Alexandra', 'Thermopompe', 'Câble internet inclus'],
      photos: [
        { url: '/listing/bathroom.png', alt: 'Salle de bain moderne', description: 'Modern bathroom with clean finishes' },
        { url: '/listing/condo_luxurious.png', alt: 'Salon neuf', description: 'Bright new condo living room with balcony' },
        { url: '/listing/modern_interior.png', alt: 'Cuisine contemporaine', description: 'Sleek kitchen with quartz countertops and stainless appliances' },
        { url: '/listing/table_dining.png', alt: 'Salle à manger', description: 'Elegant dining area with warm wood tones' },
        { url: '/listing/sofa_interior.png', alt: 'Espace de vie', description: 'Bright open living space with designer touches' },
      ]
    },
    {
      id: 7,
      slug: 'maison-vendue-aylmer',
      title: 'Maison contemporaine à Aylmer',
      address: '74 Rue des Saules, Aylmer',
      city: 'Gatineau',
      type: 'Maison',
      status: 'sold',
      featured: false,
      isNew: false,
      price: 612000,
      bedrooms: 3,
      bathrooms: 2,
      area: 1950,
      lotSize: 6800,
      yearBuilt: 2012,
      description: '',
      features: [],
      photos: [
        { url: '/listing/modern_interior.png', alt: 'Intérieur moderne', description: 'Modern open-concept interior' },
        { url: '/listing/bedroom.png', alt: 'Chambre principale', description: 'Minimal cream bedroom, layered beige bedding, tall window' },
        { url: '/listing/bathroom.png', alt: 'Salle de bain', description: 'Bright spa-like bathroom, stone surfaces, large windows' },
        { url: '/listing/sofa_interior.png', alt: 'Salon', description: 'Cozy living room with warm wood tones' },
        { url: '/sold/front.png', alt: 'Façade', description: 'Contemporary home exterior' },
      ]
    },
    {
      id: 8,
      slug: 'condo-vendu-centre',
      title: 'Condo lumineux — Centre-ville',
      address: '320 Rue Laurier, Apt 5',
      city: 'Gatineau',
      type: 'Condo',
      status: 'sold',
      featured: false,
      isNew: false,
      price: 345000,
      bedrooms: 2,
      bathrooms: 1,
      area: 980,
      yearBuilt: 2019,
      description: '',
      features: [],
      photos: [
        { url: '/listing/condo_luxurious.png', alt: 'Condo luxueux', description: 'Luxurious condo interior with premium finishes' },
        { url: '/listing/modern_interior.png', alt: 'Cuisine', description: 'Sleek kitchen with quartz countertops' },
        { url: '/listing/bathroom.png', alt: 'Salle de bain', description: 'Modern bathroom with clean finishes' },
        { url: '/listing/sofa_interior.png', alt: 'Salon', description: 'Bright open living space' },
        { url: '/sold/front.png', alt: 'Façade de l\'immeuble', description: 'Modern condo building exterior' },
      ]
    },
    {
      id: 9,
      slug: 'jumele-vendu-gatineau',
      title: 'Jumelé — Quartier familial',
      address: '55 Rue des Pins, Gatineau',
      city: 'Gatineau',
      type: 'Jumelé',
      status: 'sold',
      featured: false,
      isNew: false,
      price: 425000,
      bedrooms: 3,
      bathrooms: 2,
      area: 1600,
      lotSize: 3900,
      yearBuilt: 2014,
      description: '',
      features: [],
      photos: [
        { url: '/listing/sofa_interior.png', alt: 'Salon chaleureux', description: 'Warm and inviting living room' },
        { url: '/listing/table_dining.png', alt: 'Salle à manger', description: 'Elegant dining area with warm wood tones' },
        { url: '/listing/modern_interior.png', alt: 'Cuisine', description: 'Bright open-concept kitchen with neutral palette' },
        { url: '/listing/bedroom.png', alt: 'Chambre', description: 'Comfortable bedroom with natural light' },
        { url: '/sold/front.png', alt: 'Extérieur', description: 'Well-maintained semi-detached home exterior' },
      ]
    },
  ];

  getAll(): Property[] {
    return this.properties;
  }

  getActive(): Property[] {
    return this.properties.filter(p => p.status === 'active');
  }

  getFeatured(): Property[] {
    return this.properties.filter(p => p.featured && p.status === 'active');
  }

  getBySlug(slug: string): Property | undefined {
    return this.properties.find(p => p.slug === slug);
  }
}
